### PR TITLE
Fix O365 custom client ID setup

### LINKED ISSUE #223: Adding Office365 account hangs while searching for settings
## Your environment

TbSync version: 4.3
EAS-4-TbSync version: 4.4
Thunderbird version: 102.8.0

I am seeing this behavior on two laptops, both with the above environment. I am using an institutional account which requires Oauth2.

## Expected behavior
I am trying to add a new Office365 account to TbSync. Existing accounts sync correctly. The account I am trying to add is the same as an existing account (migrating to a new laptop). In the past this has worked seamlessly, allowing me to add the account and sync calendars etc.

## Actual behavior
Hangs at the "Searching for settings" step, requiring a force kill of Thunderbird. This occurs on both my old laptop (where I am duplicating the existing MS Exchange account) and on the new one (where there are no existing Exchange accounts).

## Steps to reproduce

Log has been sent to the email on your homepage. I used the highest level of info output.

### PR DESCRIPTION
**Pull request by jan-kiszka**
This was broken in 94fbf4ad: accountData is null during account setup, causing the customID initialization and, thus, the complete account creation to fail.

In fact, the client ID is not an account property, it's global. Therefore introduce getCustomeOauthClientID to obtain this property independent or the account.

Should resolve #223.

### CODE REVIEW

**Comment by mcicogni** [comment]
Hi, does anyone know when this pull request will be merged?

**Comment by mcicogni** [comment]
Hi, does anyone know when this pull request will be merged?
It is necessary to fix #223 .

**Comment by jan-kiszka** [comment]
Was about to ask as well...

**Comment by mcicogni** [comment]
Thanks! When should it find its way to a release?

**Comment by mvanderkruk** [comment]
Any update on a release date ?? I am unable to add a new calendar...

**Pull request merged**
