### PR TITLE
Enable customizable client ID

### PR DESCRIPTION
**Pull request by jan-kiszka**
As discussed in #200.

I'm also adding a Makefile at this chance to help Linux/Unix devs. If you don't like maintaining two package content lists, let me know, and I will drop this again.

### CODE REVIEW

**Comment by jobisoft** [comment]
I do not want my id in the preferences, can you change the code to keep it hard-coded but override if a pref is set?

**Comment by jan-kiszka** [comment]
Like this?

**Comment by jan-kiszka** [comment]
Ping for this topic.

**Comment by bufferoverflow** [comment]
@jobisoft Would be cool if you could review this?

**Comment by jan-kiszka** [comment]
Just rebased and tested with TB 102.7.1 - a fine still. Can we merge?

**Comment by jobisoft** [comment]
Could you verify, that this version works as intended, before I ship it?

[EAS-4-TbSync.zip](https://github.com/jobisoft/EAS-4-TbSync/files/11027401/EAS-4-TbSync.zip)

**Comment by jan-kiszka** [comment]
I'm actually running that version for more than a week now, and it's working fine.

**Comment by jobisoft** [comment]
I had to disable the version on ATN with this PR. See issue #223. I believe this is due to this PR. Any chance you could have a look?

**Comment by jan-kiszka** [comment]
I'm on it.

**Comment by jan-kiszka** [comment]
Please see #224

**Pull request merged**
