### PR TITLE
Updated Max Version to 88 - testing seems fine

### PR DESCRIPTION
**Pull request by denisabt**

### CODE REVIEW

**Comment by jobisoft** [comment]
daily is 86. how did you test with 88? ATN will reject this

**Comment by denisabt** [comment]
I didn't test it with 88, just read that the next version would be 88. I 
tested with the current version, after updating the manifest.

**Comment by denisabt** [comment]
Otherwise I can change the max version to 78.
But I can also cancel my PRs, no problem, if not welcome.

**Comment by jobisoft** [comment]
you have to set it to the version you have tested it with. because you cannot make assumptions about future versions.

**Comment by denisabt** [comment]
Will resubmit, want to do a few more checks.

**Pull request closed without merging**
