### PR TITLE
fix some incompatibility with Thunderbird 102+

### PR DESCRIPTION
**Pull request by kxxt**
This PR fixes some (maybe not all) incompatibilities with Thunderbird 102+.

### CODE REVIEW

**Comment by jobisoft** [comment]
Could you cancel this PR and create a new one for https://github.com/jobisoft/EAS-4-TbSync/tree/TB102 ? Thanks for your help!

**Comment by kxxt** [comment]
> Could you cancel this PR and create a new one for https://github.com/jobisoft/EAS-4-TbSync/tree/TB102 ? Thanks for your help!

I have changed the base branch to `TB102`.

**Comment by jobisoft** [comment]
Thanks, I will just merge this untested.

**Comment by kxxt** [comment]
BTW I have done the same fixes with `TBSync`. I have got my outlook calendar sync working with Thunderbird 102.

Still I'm not sure if other parts of the code base of TBSync is compatible with TB102. (I only use this addon for calendar sync)

FYI: There is no need to close and reopen a PR, because you can change the base branch by clicking the edit button.

**Pull request merged**
